#!/bin/bash

SERVER_DIR=`dirname $0`

source $SERVER_DIR/servers.sh

for (( n = 1 ; n <= ${#@} ; n++ ))
do
	eval "i=(\${$n})";
	if [ "$i" = "-s" ] 
	then
		m=$((n + 1));
		eval "i=(\${$m})";
		SITE=$i;
	elif [ "$i" = "-g" ] 
	then
		m=$((n + 1));
		eval "i=(\${$m})";
		GROUP=$i;
	elif [ "$i" = "-a" ] 
	then
		m=$((n + 1));
		eval "i=(\${$m})";
		ACTION=$i;
	fi		
done

shift 4;
args=$@;

process_server_action () 
{
        eval "serverArray=(\${$1[@]})";

        SERVER_NAME=${serverArray[0]};
        SERVER_PATH=${serverArray[1]};

        if [[ SERVER_NAME && SERVER_PATH ]];
                then

                if [ $ACTION ]; 
                        then
                        ssh $SERVER_NAME '
                        php '$SERVER_PATH'/'$ACTION'.php '$args';
                        exit;'
                else
                        echo 'Please specify an existing action';
                fi

        else
                echo 'Please enter a valid site';
        fi

}

if [ $GROUP ]; 
        then
        eval "groupArray=(\${$GROUP[@]})";
        
        for SITE in "${groupArray[@]}"
        do
                process_server_action $SITE
        done

elif [ $SITE ];
        then
        process_server_action $SITE
fi
